apiVersion: v1
kind: Pod
metadata:
  name: hostdir-aksnpwin000002
spec:
  containers:
  - name: hostdir
    image: e2eteam/busybox:1.29
    securityContext:
      windowsOptions:
        runAsUserName: ContainerAdministrator
    command:
      - sleep
      - "6600"
    volumeMounts:
    - name: host-volume
      mountPath: /host
  restartPolicy: Always
  volumes:
  - name: host-volume
    hostPath:
        path: "C:/"
        type: DirectoryOrCreate
  nodeSelector:
    "kubernetes.io/os": windows
