apiVersion: v1
kind: Pod
metadata:
  name: hostdir
spec:
  containers:
  - name: test
    image: e2eteam/busybox:1.29
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: test-volume
      mountPath: /test-volume
  restartPolicy: Always
  volumes:
  - name: test-volume
    hostPath:
        path: "C:/tmp"
        type: DirectoryOrCreate
  nodeSelector:
    "kubernetes.io/os": windows