apiVersion: v1
kind: Pod
metadata:
  name: loadgen
spec:
  containers:
    - name: busybox
      image: busybox
      command:
      - bin/sh
      - -c
      - "while sleep 0.01; do wget -q -O- http://win-webserver; done"
  nodeSelector:
    "kubernetes.io/os": linux