apiVersion: v1
kind: Pod
metadata:
  name: hostprocess-inclusterclient
  # annotations:
  #   microsoft.com/hostprocess-inherit-user: "true"
spec:
  securityContext:
    windowsOptions:
      hostProcess: true
      runAsUserName: "NT AUTHORITY\\local service"
  hostNetwork: true
  containers:
  - name: test
    imagePullPolicy: Always
    image: jsturtevant/agnhost:2.33-1-windows-amd64-1809
    command:
      - powershell
      - -c
      - start-process
      - -wait
      - -nonewwindow
      - $env:CONTAINER_SANDBOX_MOUNT_POINT\\agnhost
    args:
      - inclusterclient --poll-interval 5
  restartPolicy: Always
  nodeSelector:
    "kubernetes.io/os": windows
  tolerations:
    - key: ""
      operator: "Exists"
      effect: "NoSchedule"
---
