apiVersion: apps/v1
kind: Deployment
metadata:
  name: run-as-username-demo
  namespace: psp-example
spec:
  selector:
    matchLabels:
      app: run-as-username-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: run-as-username-demo
    spec:
      securityContext:
         windowsOptions:
           runAsUserName: "ContainerUser"
      containers:
      - name: run-as-username-demo
        image: mcr.microsoft.com/windows/servercore:ltsc2019
        command: ["ping", "-t", "localhost"]