apiVersion: v1
kind: Pod
metadata:
  name: nonroot
spec:
  containers:
    - name: nonroot
      image: mcr.microsoft.com/windows/servercore:ltsc2019
      securityContext:
        runAsNonRoot: true
      command: ["ping", "-t", "localhost"]
  nodeSelector:
    "kubernetes.io/os": "windows"