apiVersion: v1
kind: Pod
metadata:
  name: test-affinity
spec:
  containers:
  - name: test-affinity
    imagePullPolicy: Always
    image: registry.k8s.io/e2e-test-images/busybox:1.36.1-1
    command:
      - sleep
      - "3600"
    resources:
      limits:
        memory: "500Mi"
        cpu: "1"
      requests:
        memory: "500Mi"
        cpu: "1"
  restartPolicy: Always
  nodeSelector:
    "kubernetes.io/os": windows
  tolerations:
    - key: ""
      operator: "Exists"
      effect: "NoSchedule"
---
